# backstage resource
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  description: This is ${{ values.name }}
  annotations:
    dev.azure.com/project-repo: ${{ values.project }}/${{ values.name }}    
spec:
  type: service
  lifecycle: experimental
  owner: team-sre
  dependsOn:
    - resource:default/artists-db
